### ISSUE TITLE
Mesh Colored Faces component error

### ISSUE THREAD

**Issue by mnaugle-tt** [tt-acm/Spectacles.GrasshopperExporter#21]
@anagpuyol --

Getting this error with the new test build of TT Toolbox:
![image](https://cloud.githubusercontent.com/assets/3228216/11303452/08f0f024-8f71-11e5-90f6-b10525b1ff19.png)

**Comment by anagpuyol** [comment]
@mnaugle-tt  The component is working as expected. You have to provide one color per mesh face. Otherwise, you would use the regular Mesh Material (lambert, basic or phong)

![image](https://cloud.githubusercontent.com/assets/2687679/11303617/d3cfc5b8-8f71-11e5-94a8-36619632b72a.png)

**Comment by anagpuyol** [comment]
I can add a warning explaining the issue, that is for sure...

**Comment by mnaugle-tt** [comment]
Ah ok. This component should solve without a warning or error as I tried.  The fix would fall under the Grasshopper Longest List rule.  If one input receives a list longer than the other, use the last item in the shorter list for all remaining iterations.

**Comment by anagpuyol** [comment]
fixed

![image](https://cloud.githubusercontent.com/assets/2687679/11305001/870bc4d2-8f78-11e5-9a37-b33b0ea6cc91.png)
![image](https://cloud.githubusercontent.com/assets/2687679/11305015/98433dca-8f78-11e5-8873-08e47ee5a545.png)
