### ISSUE TITLE
Read opacity on mesh material color if given

### ISSUE THREAD

**Issue by mnaugle-tt** [tt-acm/Spectacles.GrasshopperExporter#24]
if a user supplies an opacity with their color into the color input, we should read that as the desired opacity unless a value is given to [o].   it doesn't look like that happens now.

![image](https://cloud.githubusercontent.com/assets/3228216/11306112/0fea1358-8f7e-11e5-98e0-f6a94f0566e5.png)

**Comment by anagpuyol** [comment]
This feature has been added for basic, lambert and phong materials
