### ISSUE TITLE
Add component to launch the web viewer

### ISSUE THREAD

**Issue by bhowes-tt** [tt-acm/Spectacles.GrasshopperExporter#5]
Good suggestion from @mnaugle-tt . Push people to the viewer app from Grasshopper.  He said this is ' @mostaphaRoudsari style '.

**Comment by JonatanS** [comment]
if(y) System.Diagnostics.Process.Start("http://core.thorntontomasetti.com/event/aec-technology-symposium-2015/");

**Comment by JonatanS** [comment]
I'll create this one today

**Comment by bhowes-tt** [comment]
Awesome - thanks @JonatanS 

I just did the same in revit.  See this issue: https://github.com/tt-acm/Spectacles.RevitExporter/issues/9

Also, I added the icon .pngs to the webviewer project if you want to use the same ones:
https://github.com/tt-acm/Spectacles.WebViewer/commit/493ac85bfb7297297351da5289e7960e6b28df7f

**Comment by JonatanS** [comment]
thank you @bhowes-tt that was helpful.
