### ISSUE TITLE
Face <> Color data matching issue

### ISSUE THREAD

**Issue by mostaphaRoudsari** [tt-acm/Spectacles.GrasshopperExporter#9]
If I don't graft faces it will take the first color for all mesh faces.
![image](https://cloud.githubusercontent.com/assets/2915573/9794524/8bdc84b6-57b9-11e5-9dad-9dc79ed84f9b.png)

Here is the file - download and rename to .gh:
![exportmeshwithcolors](https://cloud.githubusercontent.com/assets/2915573/9795387/46c42794-57be-11e5-8a6f-fca7d84e1df7.png)

This won't work:
![image](https://cloud.githubusercontent.com/assets/2915573/9795354/157d39a0-57be-11e5-9d3f-3c13d29a46a5.png)

and also this:
![image](https://cloud.githubusercontent.com/assets/2915573/9795340/041e005e-57be-11e5-8b85-ea16e1881d78.png)

but this will work which is exporting so many single mesh faces:
![image](https://cloud.githubusercontent.com/assets/2915573/9795370/2a2354fc-57be-11e5-8439-19c3cd5c384a.png)

also [this line](https://github.com/tt-acm/Spectacles.GrasshopperExporter/blob/master/src/Spectacles.GrasshopperExporter/Spectacles_MeshColoredFaces.cs#L170) doesn't look right:

``` C#
matCounter = mesh.Faces.Count = 1; // This is what it is now
matCounter = mesh.Faces.Count - 1; // I assume you want - 1
```

**Comment by anagpuyol** [comment]
@mostaphaRoudsari I just had a look at this. You are not using this component the way it's intended to. In the component you have to connect the mesh, and a list of colors per face, like this:

![image](https://cloud.githubusercontent.com/assets/2687679/9944494/ab24e7d6-5d55-11e5-92af-23fd7579ada0.png)

Could you give it a try and let me know if it works now for you?

Thanks!

**Comment by anagpuyol** [comment]
on another note, if what you want is to create separate meshes, then you can use the Lambert Material component and connect the list of faces to the component, and the list of colors to the material component. Again, let me know if this makes it clear for you!

**Comment by mostaphaRoudsari** [comment]
@anagpuyol as far as I can tell the first image that I uploaded matches your workflow and didn't work.

**Comment by anagpuyol** [comment]
I can just see now, you have the old version, the new one, has different icons for the scene. Hopefully, the sample file and the new version will make it work like a charm. Let me know how it goes

**Comment by mostaphaRoudsari** [comment]
It's fixed in the new version. Thanks @anagpuyol.
